openapi: 3.1.0
info:
  title: Welsh Vocab API
  version: "1.0.0"
servers:
  - url: https://welsh-gpt-backend-2.onrender.com
paths:
  /allowed:
    get:
      operationId: getAllowedVocab
      summary: Get unlocked Welsh vocabulary
      parameters:
        - name: section
          in: query
          required: true
          schema:
            type: integer
        - name: unit
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Allowed token list
          content:
            application/json:
              schema:
                type: object
                properties:
                  allowed:
                    type: array
                    items:
                      type: string
components: {}
